<?php

namespace Database\Seeders;

use App\Models\Banner;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\Review;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 0. Test Auth Accounts — 6 role-based users (password: password123)
        User::firstOrCreate(
            ['email' => 'admin@soziecollection.com'],
            [
                'name' => 'Sozie Super Admin',
                'phone' => '255711000001',
                'role' => User::ROLE_SUPER_ADMIN,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'manager@soziecollection.com'],
            [
                'name' => 'Store Manager',
                'phone' => '255711000002',
                'role' => User::ROLE_MANAGER,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'inventory@soziecollection.com'],
            [
                'name' => 'Inventory Manager',
                'phone' => '255711000003',
                'role' => User::ROLE_INVENTORY_MANAGER,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'orders@soziecollection.com'],
            [
                'name' => 'Orders Manager',
                'phone' => '255711000004',
                'role' => User::ROLE_ORDER_MANAGER,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'content@soziecollection.com'],
            [
                'name' => 'Content Manager',
                'phone' => '255711000005',
                'role' => User::ROLE_CONTENT_MANAGER,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        User::firstOrCreate(
            ['email' => 'customer@soziecollection.com'],
            [
                'name' => 'Test Customer',
                'phone' => '255711000006',
                'role' => User::ROLE_CUSTOMER,
                'email_verified_at' => now(),
                'password' => Hash::make('password123'),
                'remember_token' => Str::random(10),
            ]
        );

        // 1. Categories
        $categoriesData = [
            [
                'name' => "Women's Perfumes",
                'slug' => 'womens-perfumes',
                'description' => 'Sensual, elegant, and enchanting floral and fruity scents designed for women.',
                'image' => 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Floral',
            ],
            [
                'name' => "Men's Perfumes",
                'slug' => 'mens-perfumes',
                'description' => 'Bold, masculine, and charismatic woody, spicy, and amber creations.',
                'image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Woody',
            ],
            [
                'name' => 'Unisex Perfumes',
                'slug' => 'unisex-perfumes',
                'description' => 'Sophisticated genderless blends crafted with rare notes and timeless character.',
                'image' => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Intense',
            ],
            [
                'name' => 'Perfume Oils',
                'slug' => 'perfume-oils',
                'description' => 'Pure concentrated elixir oil formulas offering incredible depth and all-day longevity.',
                'image' => 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Spicy',
            ],
            [
                'name' => 'Body Mists',
                'slug' => 'body-mists',
                'description' => 'Refreshing, airy, and light fragrance mists perfect for daily hydration and fragrance layering.',
                'image' => 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Fresh',
            ],
            [
                'name' => 'Perfume Gift Sets',
                'slug' => 'perfume-gift-sets',
                'description' => 'Exquisite curations of signature fragrances beautifully presented for special moments.',
                'image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
                'mood_tag' => 'Sweet',
            ],
        ];

        $categories = [];
        foreach ($categoriesData as $cat) {
            $categories[$cat['slug']] = Category::create($cat);
        }

        // 2. Comprehensive 22 Luxury Perfumes Catalog
        $productsData = [
            // ================= WOMEN'S PERFUMES =================
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE ELEGANCE',
                'gender' => 'women',
                'price' => 65000,
                'discount_price' => 55000,
                'discount_percentage' => 15,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => false,
                'description' => 'A sophisticated fragrance created for those who want to leave a memorable impression. SOZIE ELEGANCE opens with fresh fruity notes before revealing a romantic floral heart and settling into a warm, elegant base of vanilla, musk and amber.',
                'why_you_will_love_it' => [
                    'Elegant everyday luxury fragrance',
                    'Over 12 hours of long-lasting aura',
                    'Perfect for dates, galas, and special evenings',
                    'Housed in a polygonal crystal glass bottle',
                ],
                'fragrance_family' => 'Floral Fruity',
                'scent_type' => 'Floral',
                'top_notes' => 'Italian Bergamot, Sun-Ripened Pear, Pink Pepper',
                'heart_notes' => 'Damask Rose, Moroccan Jasmine, Peony',
                'base_notes' => 'Madagascar Vanilla, Creamy Amber, White Musk',
                'concentration' => 'Eau de Parfum',
                'longevity' => '10 - 12 Hours',
                'occasion' => 'Date Night, Galas, Special Events',
                'season' => 'All Seasons',
                'time_of_day' => 'Evening & Night',
                'intensity' => 'Strong',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE VELVET ROSE',
                'gender' => 'women',
                'price' => 60000,
                'discount_price' => 48000,
                'discount_percentage' => 20,
                'is_best_seller' => false,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Dark velvety roses steeped in sweet black plum and rich hazelnut cream. SOZIE VELVET ROSE is dark, seductive, and deeply romantic for women who own every room they step into.',
                'why_you_will_love_it' => [
                    'Seductive dark floral scent trail',
                    'Compliment magnet for evening dining',
                    'Includes travel luxury atomizer',
                ],
                'fragrance_family' => 'Floral Gourmand',
                'scent_type' => 'Sweet',
                'top_notes' => 'Black Plum, Mandora Citrus, Lychee',
                'heart_notes' => 'Turkish Velvet Rose, Praline, Iris Blossom',
                'base_notes' => 'Patchouli, Dark Cacao, Sandalwood',
                'concentration' => 'Eau de Parfum',
                'longevity' => '10 Hours',
                'occasion' => 'Romance, Dinner Dates, Night Parties',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Evening',
                'intensity' => 'Medium / Strong',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE BLOSSOM BLISS',
                'gender' => 'women',
                'price' => 58000,
                'discount_price' => 50000,
                'discount_percentage' => 14,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => false,
                'description' => 'A joyful, sunlit bouquet of blooming cherry blossoms, white peach, and sparkling freesia. SOZIE BLOSSOM BLISS radiates feminine charm, lighthearted sweetness, and morning freshness.',
                'why_you_will_love_it' => [
                    'Delicate and romantic floral trail',
                    'Uplifting fresh daytime wear',
                    'Soft powdered musk finish',
                ],
                'fragrance_family' => 'Fresh Floral',
                'scent_type' => 'Floral',
                'top_notes' => 'Cherry Blossom, White Peach, Nectarine',
                'heart_notes' => 'White Freesia, Lily of the Valley, Magnolia',
                'base_notes' => 'Powdered Cedar, Sheer Musk, Cashmere Wood',
                'concentration' => 'Eau de Parfum',
                'longevity' => '8 - 10 Hours',
                'occasion' => 'Office, Brunch, Spring Weddings',
                'season' => 'Spring / Summer',
                'time_of_day' => 'Daytime',
                'intensity' => 'Medium',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE SWEET SEDUCTION',
                'gender' => 'women',
                'price' => 62000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => false,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'An addictive gourmand composition centered around caramelized almond, toasted tonka bean, and velvety Tahitian vanilla bean.',
                'why_you_will_love_it' => [
                    'Delicious gourmand aroma cloud',
                    'Irresistible sweet compliment magnet',
                    'Warm cozy skin duration',
                ],
                'fragrance_family' => 'Warm Gourmand',
                'scent_type' => 'Vanilla',
                'top_notes' => 'Sugared Almond, Salted Caramel',
                'heart_notes' => 'Heliotrope Blossom, Tonka Bean',
                'base_notes' => 'Tahitian Vanilla, Sandalwood Cream',
                'concentration' => 'Eau de Parfum',
                'longevity' => '12 Hours',
                'occasion' => 'Night Parties, Evening Dinners, Casual',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Evening',
                'intensity' => 'Strong',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE CRYSTAL JASMINE',
                'gender' => 'women',
                'price' => 70000,
                'discount_price' => 62000,
                'discount_percentage' => 11,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => true,
                'description' => 'Night-blooming royal jasmine Sambac combined with glowing orange blossom, white gardenia, and golden honeyed amber.',
                'why_you_will_love_it' => [
                    'Pure regal white floral fragrance',
                    'Hand-blown clear crystal bottle',
                    'Extremely rich sillage',
                ],
                'fragrance_family' => 'White Floral',
                'scent_type' => 'Floral',
                'top_notes' => 'Mandarin Zest, Neroli Petals',
                'heart_notes' => 'Night Jasmine Sambac, Gardenia, Orange Blossom',
                'base_notes' => 'Honeyed Amber, White Cedarwood',
                'concentration' => 'Extrait de Parfum',
                'longevity' => '14 Hours',
                'occasion' => 'Weddings, VIP Galas, High Society',
                'season' => 'All Seasons',
                'time_of_day' => 'Night',
                'intensity' => 'Intense',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'womens-perfumes',
                'name' => 'SOZIE PRINCESS AMBER',
                'gender' => 'women',
                'price' => 68000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => false,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'A royal feminine amber fragrance with sparkling pink champagne notes, candied orchids, and warm benzoin resins.',
                'why_you_will_love_it' => [
                    'Opulent oriental femininity',
                    'Gilded rose gold packaging',
                    'Long lasting sensual drydown',
                ],
                'fragrance_family' => 'Oriental Floral',
                'scent_type' => 'Oriental',
                'top_notes' => 'Pink Champagne, Wild Raspberry',
                'heart_notes' => 'Black Orchid, Red Rose, Vanilla Orchid',
                'base_notes' => 'Golden Benzoin, Amber Resin, Creamy Vanilla',
                'concentration' => 'Eau de Parfum',
                'longevity' => '12 Hours',
                'occasion' => 'Formal Evening, Red Carpet',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Night',
                'intensity' => 'Strong',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1200',
            ],

            // ================= MEN'S PERFUMES =================
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE NOIR IMPERIAL',
                'gender' => 'men',
                'price' => 75000,
                'discount_price' => 68000,
                'discount_percentage' => 10,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => true,
                'description' => 'Command presence and undeniable allure with SOZIE NOIR IMPERIAL. Designed for the modern gentleman who desires distinction. Mysterious dark oud, rich leather, and vibrant citrus harmonise to create an unforgettable signature scent.',
                'why_you_will_love_it' => [
                    'Dominant, magnetic masculine profile',
                    'Extremely high projection and sillage',
                    'Ideal for executive meetings and VIP nights',
                    'Hand-finished angular obsidian bottle',
                ],
                'fragrance_family' => 'Woody Leather',
                'scent_type' => 'Woody',
                'top_notes' => 'Calabrian Bergamot, Black Cardamom, Grapefruit',
                'heart_notes' => 'Smoky Birch, Cedarwood, Vetiver',
                'base_notes' => 'Royal Cambodian Oud, Rich Leather, Tonka Bean',
                'concentration' => 'Extrait de Parfum',
                'longevity' => '14+ Hours',
                'occasion' => 'Executive, Black Tie, Night Out',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Night',
                'intensity' => 'Intense',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE OCEANIC BREEZE',
                'gender' => 'men',
                'price' => 55000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => false,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Crisp, energetic, and invigorating like ocean air washing over crushed mint and coastal driftwoods. Built for active days, sunny afternoons, and effortless charisma.',
                'why_you_will_love_it' => [
                    'Clean, ultra-fresh morning boost',
                    'Perfect for tropical weather & gym/office',
                    'Long-lasting aquatic freshness',
                ],
                'fragrance_family' => 'Aquatic Citrus',
                'scent_type' => 'Fresh',
                'top_notes' => 'Sea Salt, Lime Zest, Crushed Mint Leaves',
                'heart_notes' => 'Marine Accord, Lavender, Sage',
                'base_notes' => 'Driftwood, White Amber, Oakmoss',
                'concentration' => 'Eau de Toilette',
                'longevity' => '8 Hours',
                'occasion' => 'Everyday, Office, Sport, Summer Outings',
                'season' => 'Spring / Summer',
                'time_of_day' => 'Daytime',
                'intensity' => 'Medium',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE ROYAL VETIVER',
                'gender' => 'men',
                'price' => 70000,
                'discount_price' => 60000,
                'discount_percentage' => 14,
                'is_best_seller' => true,
                'is_featured' => false,
                'is_new_arrival' => false,
                'is_limited_edition' => false,
                'description' => 'A refined woody composition combining earthy Haitian vetiver, spiced pink pepper, and smoked cedarwood. Sharp, charismatic, and intensely masculine.',
                'why_you_will_love_it' => [
                    'Distinguished executive scent profile',
                    'Smooth vetiver drydown',
                    'High compliment rate in professional settings',
                ],
                'fragrance_family' => 'Earthy Woody',
                'scent_type' => 'Woody',
                'top_notes' => 'Grapefruit Zest, Pink Peppercorn',
                'heart_notes' => 'Haitian Vetiver, Bourbon Geranium',
                'base_notes' => 'Atlas Cedar, Patchouli, Benzoin Resin',
                'concentration' => 'Eau de Parfum',
                'longevity' => '12 Hours',
                'occasion' => 'Business, Boardroom, Formal Dinners',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Strong',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE LEATHER COMMANDER',
                'gender' => 'men',
                'price' => 78000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => false,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => true,
                'description' => 'Unapologetically bold leather fragrance fused with smoked tobacco leaf, roasted coffee bean, and dark amber. Made for the fearless leader.',
                'why_you_will_love_it' => [
                    'Intense masculine leather presence',
                    'Unrivaled projection in cool evenings',
                    'Sleek matte black metallic bottle',
                ],
                'fragrance_family' => 'Smoky Leather',
                'scent_type' => 'Woody',
                'top_notes' => 'Wild Thyme, Saffron, Raspberry',
                'heart_notes' => 'Tuscan Leather, Coffee Bean, Frankincense',
                'base_notes' => 'Dark Amber, Tobacco Leaf, Suede Accord',
                'concentration' => 'Extrait de Parfum',
                'longevity' => '16 Hours',
                'occasion' => 'VIP Clubbing, Night Drives, Black Tie',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Night',
                'intensity' => 'Intense',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE CITRUS SATORI',
                'gender' => 'men',
                'price' => 52000,
                'discount_price' => 45000,
                'discount_percentage' => 13,
                'is_best_seller' => false,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Bright Sicilian lemon, bergamot rind, and crushed cardamom over a crisp cypress and cedarwood base.',
                'why_you_will_love_it' => [
                    'Zesty uplifting citrus burst',
                    'Ideal for warm weather & sports',
                    'Crisp clean woody drydown',
                ],
                'fragrance_family' => 'Citrus Woody',
                'scent_type' => 'Fresh',
                'top_notes' => 'Sicilian Lemon, Blood Orange, Cardamom',
                'heart_notes' => 'Cypress Wood, Clary Sage, Juniper Berries',
                'base_notes' => 'Cedarwood, Vetiver, Sheer Musk',
                'concentration' => 'Eau de Toilette',
                'longevity' => '8 Hours',
                'occasion' => 'Casual, Gym, Daytime Outings',
                'season' => 'Spring / Summer',
                'time_of_day' => 'Daytime',
                'intensity' => 'Medium',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'mens-perfumes',
                'name' => 'SOZIE AMBER KING',
                'gender' => 'men',
                'price' => 72000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => false,
                'description' => 'Glowing golden amber fused with spicy nutmeg, Madagascar vanilla, and roasted tonka bean.',
                'why_you_will_love_it' => [
                    'Warm magnetic masculine aura',
                    'Incredible evening projection',
                    'Luxurious gold trim bottle',
                ],
                'fragrance_family' => 'Oriental Amber',
                'scent_type' => 'Spicy',
                'top_notes' => 'Spicy Nutmeg, Cinnamon, Lavender',
                'heart_notes' => 'Amberwood, Guaiac Wood, Myrrh',
                'base_notes' => 'Golden Amber, Madagascar Vanilla, Leather',
                'concentration' => 'Eau de Parfum',
                'longevity' => '12+ Hours',
                'occasion' => 'Date Night, Galas, Special Occasions',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Night',
                'intensity' => 'Strong',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1594035910387-fea47794261f?auto=format&fit=crop&q=80&w=1200',
            ],

            // ================= UNISEX PERFUMES =================
            [
                'category' => 'unisex-perfumes',
                'name' => 'SOZIE GOLDEN AURA',
                'gender' => 'unisex',
                'price' => 85000,
                'discount_price' => null,
                'discount_percentage' => null,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Envelop yourself in pure luxury. SOZIE GOLDEN AURA captures radiant golden sunlight infused with warm saffron, velvety amber, and gourmand vanilla. An intoxicating masterpiece suitable for every gender.',
                'why_you_will_love_it' => [
                    'Warm, glowing gourmand warmth',
                    'Completely unisex signature character',
                    'Unrivaled 16-hour duration',
                    'Gilded champagne gold polygonal bottle',
                ],
                'fragrance_family' => 'Oriental Amber',
                'scent_type' => 'Vanilla',
                'top_notes' => 'Kashmiri Saffron, Sliced Almond, Blood Orange',
                'heart_notes' => 'Amberwood, White Jasmine, Honeycomb',
                'base_notes' => 'Bourbon Vanilla, Cedar Resin, Crystal Amber',
                'concentration' => 'Eau de Parfum',
                'longevity' => '12 - 16 Hours',
                'occasion' => 'Everyday, Celebration, Luxury Outings',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Strong',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
                    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'unisex-perfumes',
                'name' => 'SOZIE SATORI BLEND',
                'gender' => 'unisex',
                'price' => 80000,
                'discount_price' => 72000,
                'discount_percentage' => 10,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => true,
                'description' => 'A meditative oriental creation combining rare Japanese incense, smoked cedar, and creamy sandalwood with sparkling pink peppercorns.',
                'why_you_will_love_it' => [
                    'Serene oriental incense profile',
                    'Universally loved unisex scent trail',
                    'Long lasting calming drydown',
                ],
                'fragrance_family' => 'Oriental Spice',
                'scent_type' => 'Spicy',
                'top_notes' => 'Pink Peppercorn, Yuzu Zest, Bergamot',
                'heart_notes' => 'Kyoto Incense, Cypress, White Tea',
                'base_notes' => 'Mysore Sandalwood, Guaiac Wood, Sheer Musk',
                'concentration' => 'Eau de Parfum',
                'longevity' => '14 Hours',
                'occasion' => 'Meditation, Executive, Fine Dining',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Intense',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'unisex-perfumes',
                'name' => 'SOZIE SILK OUD',
                'gender' => 'unisex',
                'price' => 88000,
                'discount_price' => 78000,
                'discount_percentage' => 11,
                'is_best_seller' => false,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Smooth silky Laotian agarwood combined with Bulgarian rose petals, chamomile, and warm vanilla syrup.',
                'why_you_will_love_it' => [
                    'Velvety smooth non-harsh oud',
                    'Exquisite floral oud balance',
                    'Opulent crystal bottle presentation',
                ],
                'fragrance_family' => 'Floral Oud',
                'scent_type' => 'Intense',
                'top_notes' => 'Bulgarian Rose, Blue Chamomile',
                'heart_notes' => 'Laotian Oud Wood, Papyrus',
                'base_notes' => 'Vanilla Absolute, Golden Amber, Musk',
                'concentration' => 'Extrait de Parfum',
                'longevity' => '16+ Hours',
                'occasion' => 'Weddings, VIP Galas, Royal Events',
                'season' => 'Autumn / Winter',
                'time_of_day' => 'Night',
                'intensity' => 'Intense',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=1200',
            ],

            // ================= PERFUME OILS =================
            [
                'category' => 'perfume-oils',
                'name' => 'SOZIE ROYAL OUD OIL',
                'gender' => 'unisex',
                'price' => 45000,
                'discount_price' => 40000,
                'discount_percentage' => 11,
                'is_best_seller' => true,
                'is_featured' => false,
                'is_new_arrival' => false,
                'is_limited_edition' => true,
                'description' => 'Pure 100% concentrated perfume oil without alcohol. Rich oriental oud fused with sweet vanilla, spicy nutmeg, and glowing amber. A single drop lasts well over 24 hours.',
                'why_you_will_love_it' => [
                    '0% Alcohol concentrate perfume oil',
                    'Unbeatable 24+ hour skin scent retention',
                    'Ideal for layering with spray perfumes',
                ],
                'fragrance_family' => 'Oriental Spicy',
                'scent_type' => 'Spicy',
                'top_notes' => 'Nutmeg, Cinnamon Bark, Cardamom',
                'heart_notes' => 'Smoky Incense, Rose absolute, Agarwood',
                'base_notes' => 'Pure Oud Wood, Sandalwood, Golden Musk',
                'concentration' => 'Concentrated Perfume Oil',
                'longevity' => '24+ Hours',
                'occasion' => 'Weddings, Formal Gatherings, Night Prayer',
                'season' => 'All Seasons',
                'time_of_day' => 'Evening & Night',
                'intensity' => 'Intense',
                'sillage' => 'Strong',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'perfume-oils',
                'name' => 'SOZIE SAFARI WOODS OIL',
                'gender' => 'unisex',
                'price' => 42000,
                'discount_price' => 38000,
                'discount_percentage' => 10,
                'is_best_seller' => false,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Concentrated oil capturing African sandalwood, golden amber, wild honey, and toasted vanilla bean.',
                'why_you_will_love_it' => [
                    'Alcohol-free pure oil formula',
                    'Smooth warm skin scent',
                    'Perfect compact rollerball packaging',
                ],
                'fragrance_family' => 'Warm Wood',
                'scent_type' => 'Woody',
                'top_notes' => 'Wild Honey, Cinnamon Leaf',
                'heart_notes' => 'African Sandalwood, Amberwood',
                'base_notes' => 'Vanilla Bean, Cashmere Musk',
                'concentration' => 'Concentrated Perfume Oil',
                'longevity' => '20 Hours',
                'occasion' => 'Everyday, Travel, Casual Evening',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Strong',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?auto=format&fit=crop&q=80&w=1200',
            ],

            // ================= BODY MISTS =================
            [
                'category' => 'body-mists',
                'name' => 'SOZIE MYSTIC VANILLA MIST',
                'gender' => 'women',
                'price' => 30000,
                'discount_price' => 25000,
                'discount_percentage' => 17,
                'is_best_seller' => false,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'Warm, cozy, and irresistible gourmand body mist infused with creamy vanilla bean, coconut milk, and toasted marshmallow.',
                'why_you_will_love_it' => [
                    'Lighthearted daily indulgence mist',
                    'Hydrating Aloe Vera formula',
                    'Sweet comforting scent cloud',
                ],
                'fragrance_family' => 'Gourmand Vanilla',
                'scent_type' => 'Vanilla',
                'top_notes' => 'Coconut Water, Whipped Cream',
                'heart_notes' => 'Bourbon Vanilla, Caramel Drizzle',
                'base_notes' => 'Toasted Marshmallow, Sheer Amber',
                'concentration' => 'Body Mist',
                'longevity' => '6 Hours',
                'occasion' => 'Everyday, Post-Shower, Casual Outings',
                'season' => 'All Seasons',
                'time_of_day' => 'Daytime',
                'intensity' => 'Light / Medium',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'body-mists',
                'name' => 'SOZIE PARADISO MIST',
                'gender' => 'unisex',
                'price' => 32000,
                'discount_price' => 28000,
                'discount_percentage' => 12,
                'is_best_seller' => true,
                'is_featured' => false,
                'is_new_arrival' => true,
                'is_limited_edition' => false,
                'description' => 'An invigorating tropical body mist infused with passionfruit nectar, sparkling coconut water, and white hibiscus.',
                'why_you_will_love_it' => [
                    'Refreshing tropical fragrance burst',
                    'Hydrating fine mist spray',
                    'Perfect for hot sunny days & beach outings',
                ],
                'fragrance_family' => 'Tropical Fresh',
                'scent_type' => 'Fresh',
                'top_notes' => 'Passionfruit, Mango Nectar, Lime Zest',
                'heart_notes' => 'White Hibiscus, Coconut Water, Jasmine',
                'base_notes' => 'Solar Amber, Driftwood, Sheer Musk',
                'concentration' => 'Body Mist',
                'longevity' => '6 Hours',
                'occasion' => 'Beach, Casual, Post-Workout',
                'season' => 'Spring / Summer',
                'time_of_day' => 'Daytime',
                'intensity' => 'Light / Medium',
                'sillage' => 'Moderate',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&q=80&w=1200',
            ],

            // ================= GIFT SETS =================
            [
                'category' => 'perfume-gift-sets',
                'name' => 'SOZIE SIGNATURE TRILOGY BOX',
                'gender' => 'unisex',
                'price' => 130000,
                'discount_price' => 110000,
                'discount_percentage' => 15,
                'is_best_seller' => true,
                'is_featured' => true,
                'is_new_arrival' => false,
                'is_limited_edition' => true,
                'description' => 'The ultimate luxury gift box featuring three 30ml signature perfumes: Sozie Elegance, Sozie Noir Imperial, and Sozie Golden Aura in a custom velvet-lined geometric showcase case.',
                'why_you_will_love_it' => [
                    '3 Full 30ml premium bottles included',
                    'Exquisite gift-ready geometric box presentation',
                    'Unmatched versatility for every mood and event',
                ],
                'fragrance_family' => 'Discovery Set',
                'scent_type' => 'Floral',
                'top_notes' => 'Assorted Signature Top Notes',
                'heart_notes' => 'Assorted Signature Heart Notes',
                'base_notes' => 'Assorted Signature Base Notes',
                'concentration' => 'Eau de Parfum Trio',
                'longevity' => '12+ Hours',
                'occasion' => 'Gifting, Birthdays, Anniversaries, VIP Gift',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Strong',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1200',
            ],
            [
                'category' => 'perfume-gift-sets',
                'name' => 'SOZIE ROYAL COUTURE SET',
                'gender' => 'women',
                'price' => 140000,
                'discount_price' => 125000,
                'discount_percentage' => 11,
                'is_best_seller' => false,
                'is_featured' => true,
                'is_new_arrival' => true,
                'is_limited_edition' => true,
                'description' => 'A royal gift box designed for queenly elegance. Features 50ml Sozie Elegance, 10ml travel spray, and 100ml matching velvet body lotion.',
                'why_you_will_love_it' => [
                    'Includes 50ml perfume, travel spray & scented lotion',
                    'Royal gold velvet gift box',
                    'Complete fragrance layering experience',
                ],
                'fragrance_family' => 'Floral Luxury',
                'scent_type' => 'Floral',
                'top_notes' => 'Italian Bergamot, Pear',
                'heart_notes' => 'Rose, Jasmine, Peony',
                'base_notes' => 'Vanilla, White Amber, Musk',
                'concentration' => 'Eau de Parfum Set',
                'longevity' => '14 Hours',
                'occasion' => 'Bridal Gift, Birthday, Special Occasion',
                'season' => 'All Seasons',
                'time_of_day' => 'Day & Night',
                'intensity' => 'Strong',
                'sillage' => 'Enormous',
                'video_url' => 'https://youtu.be/WhKJl9W_1Fw',
                'images' => [
                    'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=800',
                ],
                'campaign_image' => 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=1200',
            ],
        ];

        foreach ($productsData as $index => $item) {
            $catSlug = $item['category'];
            unset($item['category']);

            $item['category_id'] = $categories[$catSlug]->id;
            $item['slug'] = Str::slug($item['name']);
            $item['sku'] = 'SZ-'.strtoupper(Str::random(5));

            $product = Product::create($item);

            // Add standard clean size variants: 10ml, 30ml, 50ml, 100ml
            $basePrice = $product->price;
            $variants = [
                ['size' => '10ml', 'price' => round($basePrice * 0.25, -3)],
                ['size' => '30ml', 'price' => round($basePrice * 0.55, -3)],
                ['size' => '50ml', 'price' => $basePrice],
                ['size' => '100ml', 'price' => round($basePrice * 1.6, -3)],
            ];

            foreach ($variants as $v) {
                ProductVariant::create([
                    'product_id' => $product->id,
                    'size' => $v['size'],
                    'price' => $v['price'],
                    'stock_quantity' => 50,
                ]);
            }

            // Reviews
            Review::create([
                'product_id' => $product->id,
                'customer_name' => 'Amina K.',
                'rating' => 5,
                'comment' => 'Harufu hii ni ya kipekee sana! Kila ninapopita watu wanaulizia perfume gani nimepaka. Highly recommended!',
                'is_verified' => true,
            ]);

            Review::create([
                'product_id' => $product->id,
                'customer_name' => 'David M.',
                'rating' => 5,
                'comment' => 'The longevity is unmatched. Stayed on my suit jacket for 2 full days. Amazing packaging!',
                'is_verified' => true,
            ]);
        }

        // 3. Marketing Banners
        Banner::updateOrCreate(
            ['title' => 'SOZIE COLLECTION'],
            [
                'eyebrow' => 'THE ATELIER VISUAL EXPERIENCE',
                'headline' => 'YOUR SCENT.',
                'highlight_text' => 'YOUR SIGNATURE.',
                'subtitle' => 'Discover handcrafted fragrances designed to leave a memorable impression.',
                'image' => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&q=80&w=1200',
                'button_text' => 'EXPLORE COLLECTION',
                'button_link' => '/shop',
                'secondary_button_text' => 'FIND YOUR SCENT',
                'secondary_button_link' => '/#scent-finder',
                'is_active' => true,
                'sort_order' => 1,
            ]
        );
    }
}
